application: bitcoingae
version: 3
runtime: python
api_version: 1

handlers:
- url: /channel.js
  static_files: channel.js
  upload: channel.js

- url: .*
  script: main.py

inbound_services:
- channel_presence